### ISSUE TITLE
Clear terminal screen before rendering TopFrame

### ISSUE THREAD

**Issue by business-phil** [wagoodman/jotframe#9]
When a user has output on most lines of the terminal and then they use TopFrame, we write over their preexisting output and most of it is still visible below TopFrame.  In order to preserve previous output for users, we should identify a solution that does not affect earlier output.

I'll add a screenshot later to clarify the issue.

**Comment by business-phil** [comment]
I've never interacted with ansi control characters, so I'll have to investigate that option.
I tried adding the middle line here to NewTopFrame, but that just clears the screen and makes it look like a BottomFrame:
```
defer frame.frame.updateAndDraw()

frame.frame.rowAdvancements += (terminalHeight - frame.frame.height())

return frame
```

We haven't talked about `updateAndDraw()` yet, but it looks like this might be where `TopFrame.update()` comes into play?

**Comment by business-phil** [comment]
Correction, it looks like the middle line above would essentially get called at the same time if I were to put it in `update()`.

**Comment by business-phil** [comment]
😞  I've been trying to clear the terminal using https://github.com/nsf/termbox-go both in the example and in the TopFrame initializer, but still no luck.

**Comment by wagoodman** [comment]
With the ansi control approach, checkout http://www.termsys.demon.co.uk/vtansi.htm (specifically "Erase Screen"). An example of how to do this is here: https://github.com/buger/goterm/blob/master/terminal.go#L111 . Essentially a `fmt.Print(""\033[2J"")` will do, however, there may be times where doing the rowAdvancements makes more sense (such as when we want to preserver the terminal history)
